### ISSUE TITLE
cannot be removed

### ISSUE THREAD

**Issue by excaliburkim** [Lama06/Schneckenhaus#1]
Thank you for developing such a great plugin.
I'd like to put it to good use on our server.
It is causing a conflict with a plugin being used on our servers.
The shulker box can be installed, but cannot be removed.
The plugin I am using is https://www.spigotmc.org/resources/blockprot.87829/
Could you please make it work for me?

Additionally, there is a feature I would like to request.
I would like to allow only administrators to create this shulker box. Is it possible?

I really want to use it on my server!

**Comment by Lama06** [comment]
Regarding your feature request, I now added support for a permission that allows players to craft snail shells.

**Comment by excaliburkim** [comment]
Thank you for the correction regarding permissions.
By any chance, is a delete command possible?
For example, like below:
/sh delete <id>

**Comment by Lama06** [comment]
I added this feature and published an update. You can now execute /sh delete <id> to delete a snail shell.
After that, a player can't enter this snail shell anymore. If he or she tries to do so, the shulker box block will be removed.

**Comment by excaliburkim** [comment]
wow!
Your development drive is amazing.
I think you will become a great developer in the future!
thank you
I’ll use it well on our server!

**Comment by excaliburkim** [comment]
![2024-05-24 12 27 27](https://github.com/Lama06/Schneckenhaus/assets/41064236/952871bb-2465-4a35-9b3e-e9e73dd19a57)
![2024-05-24 12 27 58](https://github.com/Lama06/Schneckenhaus/assets/41064236/7b48f04d-02ac-4784-8e29-a17fbcdd34c8)
I filled the perimeter of the room with boxes, except for the door.
When I try to get into the room, I'm on the roof.
There is no way out.

**Comment by Lama06** [comment]
I published an update that should fix this. Does it work for you now?
