### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by frank267195** [Lama06/Schneckenhaus#2]
Hello, does this plug-in support the paper server?
I use paper 1.20.2

**Comment by Lama06** [comment]
Yes, the plugins works on Paper servers. However, it uses a functionality which isn't present in 1.20.2. You should update to 1.20.4 or 1.20.6 of Paper.

**Comment by frank267195** [comment]
Isn’t it possible to use a lower version of the plug-in?

**Comment by Lama06** [comment]
No unfortunately not, because I initially developed the plugin when 1.20.4 was the most recent version.

**Comment by frank267195** [comment]
I changed to 1.20.4 and it works, thanks
